version: '3.7'
services:
  notes-app-backend:
    build:
      context: C:\Users\Eps\Documents\GitHub\NotesApplication
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - C:\Users\Eps\Documents\GitHub\NotesApplication:/usr/src/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notesdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  notes-app-frontend:
    build:
      context: C:\Users\Eps\Documents\GitHub\notes-app
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - C:\Users\Eps\Documents\GitHub\notes-app:/usr/src/app

  db:
    image: postgres:15.3
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=notesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
